apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking-backend-deployment
spec:
  selector:
    matchLabels:
      app: tracking-backend-deployment
  template:
    metadata:
      labels:
        app: tracking-backend-deployment
        editor: vscode
    spec:
      containers:
      - name: tracking-backend-container
        image: tracking_backend:v1
        ports: 
          - containerPort: 8085
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: springboot-config
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: springboot-config
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: springboot-config
              key: SPRING_DATASOURCE_PASSWORD
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          valueFrom:
            configMapKeyRef:
              name: springboot-config
              key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          valueFrom:
            configMapKeyRef:
              name: springboot-config
              key: SPRING_JPA_HIBERNATE_DDL_AUTO
        - name: SPRING_JPA_SHOW_SQL
          valueFrom:
            configMapKeyRef:
              name: springboot-config
              key: SPRING_JPA_SHOW_SQL
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
          valueFrom:
            configMapKeyRef:
              name: springboot-config
              key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT