apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  username: cG9zdGdyZXM=   # => command in linux = echo -n "postgres" | base64
  password: cm9vdA==       # base64 encoded value of 'root'
